"""Generate REPO_MAP.md: directory tree plus per-file Python API signatures.

Usage:
    python scripts/gen_repo_map.py [--root <path>]

Walks the repository (file list comes from git ls-files, so .gitignore is
respected exactly), then writes REPO_MAP.md at the repo root with:
    - a MANUAL region: content between <!-- MANUAL:BEGIN --> and
      <!-- MANUAL:END --> is preserved verbatim across regenerations
    - a generated region: directory tree, then per Python file the top-level
      classes and functions as signatures (name, args, return annotation)
      with the first line of each docstring; other files get one line with
      file type and line count (binaries get type only)

Output is deterministic: alphabetical ordering, no timestamps. Regenerating
with no repo changes produces a byte-identical file.

Uses ast parsing only, never imports or executes repo code. Exits nonzero,
listing the offending files, if any Python file cannot be parsed; no output
file is written in that case.
"""
import argparse
import ast
import re
import subprocess
import sys
from pathlib import Path

OUTPUT_NAME = "REPO_MAP.md"
MANUAL_BEGIN = "<!-- MANUAL:BEGIN -->"
MANUAL_END = "<!-- MANUAL:END -->"
MANUAL_PLACEHOLDER = (
    "TODO: add author-maintained orientation notes here (architecture summary,\n"
    "invariants, gotchas). Content between the MANUAL markers survives regeneration."
)
HEADER = (
    "# Repo Map\n"
    "\n"
    "Generated by `scripts/gen_repo_map.py`. Edit only the MANUAL region below;\n"
    "everything after it is overwritten on regeneration. Regenerate after\n"
    "structural changes: `python scripts/gen_repo_map.py`"
)


def list_repo_files(root: Path) -> list[str]:
    """Return sorted repo-relative paths of all non-ignored files, via git."""
    result = subprocess.run(
        ["git", "-C", str(root), "ls-files", "--cached", "--others", "--exclude-standard"],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(f"git ls-files failed in {root}: {result.stderr.strip()}", file=sys.stderr)
        sys.exit(1)
    paths = sorted(
        line for line in result.stdout.splitlines()
        if line and line != OUTPUT_NAME and (root / line).is_file()
    )
    return paths


def build_tree(paths: list[str]) -> dict:
    """Nest path strings into a dict tree; leaves are None."""
    tree: dict = {}
    for path in paths:
        node = tree
        parts = path.split("/")
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = None
    return tree


def render_tree(node: dict, indent: int, lines: list[str]) -> None:
    """Render the tree as indented text, directories first, alphabetical."""
    dirs = sorted(name for name, child in node.items() if isinstance(child, dict))
    files = sorted(name for name, child in node.items() if child is None)
    for name in dirs:
        lines.append("    " * indent + name + "/")
        render_tree(node[name], indent + 1, lines)
    for name in files:
        lines.append("    " * indent + name)


def signature(node: ast.AST) -> str:
    """One-line signature for a top-level class or function, plus docstring."""
    if isinstance(node, ast.ClassDef):
        bases = ", ".join(ast.unparse(base) for base in node.bases)
        head = f"class {node.name}({bases})" if bases else f"class {node.name}"
    else:
        prefix = "async def" if isinstance(node, ast.AsyncFunctionDef) else "def"
        returns = f" -> {ast.unparse(node.returns)}" if node.returns else ""
        head = f"{prefix} {node.name}({ast.unparse(node.args)}){returns}"
    doc = ast.get_docstring(node)
    if doc:
        first_line = doc.strip().splitlines()[0].strip()
        return f"{head}: {first_line}"
    return head


def summarize_python(source: bytes) -> list[str]:
    """Signatures of top-level classes and functions. Raises SyntaxError."""
    module = ast.parse(source)
    return [
        signature(node)
        for node in module.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
    ]


def describe_other(path: Path) -> str:
    """One-line type and line count; binaries get type only."""
    data = path.read_bytes()
    label = path.suffix.lstrip(".").lower() or "text"
    if b"\x00" in data:
        return f"{label} (binary)"
    line_count = data.count(b"\n") + (1 if data and not data.endswith(b"\n") else 0)
    return f"{label}, {line_count} lines"


def extract_manual_region(output_path: Path) -> str:
    """Existing MANUAL region content, or the TODO placeholder if absent."""
    if output_path.exists():
        text = output_path.read_text(encoding="utf-8")
        match = re.search(
            re.escape(MANUAL_BEGIN) + r"\n(.*?)\n" + re.escape(MANUAL_END),
            text,
            re.DOTALL,
        )
        if match:
            return match.group(1)
    return MANUAL_PLACEHOLDER


def generate(root: Path) -> str:
    """Build the full REPO_MAP.md text for the repo at root."""
    paths = list_repo_files(root)

    parse_failures: list[str] = []
    python_sections: list[str] = []
    other_lines: list[str] = []
    for rel in paths:
        file_path = root / rel
        if file_path.suffix == ".py":
            try:
                entries = summarize_python(file_path.read_bytes())
            except SyntaxError as exc:
                parse_failures.append(f"{rel}: {exc.msg} (line {exc.lineno})")
                continue
            body = "\n".join(f"- {entry}" for entry in entries) or "(no top-level definitions)"
            python_sections.append(f"### {rel}\n\n{body}")
        else:
            other_lines.append(f"- {rel}: {describe_other(file_path)}")

    if parse_failures:
        print("Unparseable Python files, map not written:", file=sys.stderr)
        for failure in parse_failures:
            print(f"  {failure}", file=sys.stderr)
        sys.exit(1)

    tree_lines: list[str] = []
    render_tree(build_tree(paths), 0, tree_lines)

    parts = [
        HEADER,
        MANUAL_BEGIN + "\n" + extract_manual_region(root / OUTPUT_NAME) + "\n" + MANUAL_END,
        "## Directory tree\n\n```\n" + "\n".join(tree_lines) + "\n```",
        "## Python API\n\n" + "\n\n".join(python_sections),
        "## Other files\n\n" + "\n".join(other_lines),
    ]
    return "\n\n".join(parts) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate REPO_MAP.md at the repo root.")
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parent.parent,
        help="Repo root to map (default: this repo)",
    )
    args = parser.parse_args()
    root = args.root.resolve()
    if not root.is_dir():
        print(f"Not a directory: {root}", file=sys.stderr)
        sys.exit(1)
    content = generate(root)
    output_path = root / OUTPUT_NAME
    with open(output_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)
    print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
